### ISSUE TITLE
[Error] Unable to set wemo smart plug

### ISSUE THREAD

**Issue by sawjai** [menahishayan/HomeScript#14]
When I use hs.py to set wemo smart plug on/off, I got this exception
Traceback (most recent call last):
  File "/root/hs.py", line 91, in <module>
    hs.setStates(sys.argv[argumentLength-1] or None)
  File "/usr/local/lib/python3.9/dist-packages/homescript/__init__.py", line 124, in setStates
    item['value'][0]['value'] = int(value)
IndexError: list index out of range.

I try to debug the problem, and I found if I make minor change to "/usr/local/lib/python3.9/dist-packages/homescript/__init__.py" file, it fixes the issue.  See attached  modified __init__.py, I am not sure if there is any other place that need to modify.

[homescript_debug_2022.03.09.log](https://github.com/menahishayan/HomeScript/files/8216469/homescript_debug_2022.03.09.log)
[__init__.py.gz](https://github.com/menahishayan/HomeScript/files/8216536/__init__.py.gz)

**Comment by menahishayan** [comment]
Hi, thank you for identifying issues and contributing. It would be great if you could fork this repo and create a PR with your changes. 

Apologies, since I haven't been able to find the time with my day job to actually debug and evaluate these issues.

**Comment by job2310** [comment]
@sawjai Thanks for that, I was seeing the same error.  Your fix works for me however I'm getting Response 470 errors now.  Any thoughts?
