### ISSUE TITLE
AttributeError: 'HomeScript' object has no attribute 'debug'

### ISSUE THREAD

**Issue by nikoskontothanasis** [menahishayan/HomeScript#16]
Hello, 

I am facing the below issue: 

> $python3 hs.py -s Tapo Lamp 0
> 
> Traceback (most recent call last):
>   File "/Users/HomeScript/homescript/__init__.py", line 45, in getAccessories
>     interfaces.append({'iid':i['iid'],'description':  #i['description'],'maxValue': i['maxValue'],'minValue': i['minValue'],'minStep': i['minStep'], 'value': i['value']})
> KeyError: 'maxValue'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/HomeScript/hs.py", line 56, in <module>
>     hs = homescript.HomeScript(__HOSTNAME__,__PORT__,__AUTH__, args.debug, sys.argv)
>   File "/Users/HomeScript/homescript/__init__.py", line 24, in __init__
>     self.getAccessories()
>   File "/Users/HomeScript/homescript/__init__.py", line 51, in getAccessories
>     if self.debug:
> AttributeError: 'HomeScript' object has no attribute 'debug'

Any ideas? 
Thanks :)

**Comment by bsbrum** [comment]
I was having the same issue, and it turned out to be the port number in hs.py was wrong.

Check your Homebridge Config screen and make sure that you're using the port specified in the 'bridge' section, not the port you use in the browser.

<img width="249" alt="Screenshot 2022-11-18 181001" src="https://user-images.githubusercontent.com/24815138/202818180-4731eb32-3ec3-4226-827a-4939f89c5009.png">
